### ISSUE TITLE
Check for existing fallback to avoid duplication

### ISSUE THREAD

**Issue by kmuncie** [silvermine/postcss-css-var-fallback#5]
If a fallback has already been added to the CSS the plugin will continually add a new fallback. This can happen if one has been added manually or if an included stylesheet was previously processed by this plugin. 

```css
.jwac .du-color--gold-700 {
    color: #9b6d17 !important;
    color: #9b6d17 !important;
    color: var(--du-color--gold-700, #9b6d17) !important;
}
```

The plugin should not add another fallback if one currently exists.
